version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: non-root.Dockerfile
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/usr/data/app
    environment:
      - DB_URL=postgresql+asyncpg://dbuser:pass123@db:5432/cplabdb
#    env_file:
#      - .env
    healthcheck:
      test:
        - CMD
        - wget -S --spider http://localhost:8000/docs
      interval: 30s
      timeout: 30s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=cplabdb
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - 'cp-lab-vol:/var/lib/postgresql/data/'
  web:
    image: nginx:latest
    volumes:
      - ./assets/nginx/nginx.http.config:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
    -  fastapi

volumes:
  cp-lab-vol: