resources:
  requests:
    memory: 512Mi
replicas: 1
persistence:
  size: 1Gi
mode: standalone
rootUser: rootuser
rootPassword: rootpass123
consoleIngress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - minio.tsadimas.dns-cloud.net
  tls:
    - secretName: minio-production-certificate
      hosts:
        - "minio.tsadimas.dns-cloud.net"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
